version: '3'

services:
  printapi:
    container_name: printapi
    image: ghcr.io/suchmememanyskill/unifiedprintapi:latest
    restart: unless-stopped
    ports:
      - 1338:8080
    environment:
      - BASE_URL=nourl4u
    volumes:
      - ./storage:/app/storage
